#!/usr/bin/env python3
"""Embed the brain/ files into a generated Swift source so the app ships them
self-contained (no bundle-resource path fragility). Re-run whenever brain/ changes."""
import os, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
BRAIN = ROOT / "brain"
OUT = ROOT / "rounds" / "Brain" / "BrainResources.swift"

# (swift constant name, relative path under brain/, placeholder-if-missing)
FILES = [
    ("claudeMd",        "claude/CLAUDE.md",                 "# Rounds brain (missing)\n"),
    ("systemCompact",   "prompts/system_compact.txt",       "Rounds safety contract (missing).\n"),
    ("intakePrompt",    "prompts/intake.md",                "## intake (missing)\n"),
    ("intakeBatch",     "prompts/intake_batch.md",          "## batch intake (missing)\n"),
    ("hypothesesPrompt","prompts/hypotheses.md",            "## hypotheses (missing)\n"),
    ("chatPrompt",      "prompts/chat.md",                  "## chat (missing)\n"),
    ("settingsJson",    "settings.json",                    '{"permissions":{"deny":["Bash"]}}\n'),
    ("mcpTemplate",     "mcp.json.template",                '{"mcpServers":{}}\n'),
    ("criticalValues",  "critical-values.json",             '{"version":"0","note":"placeholder","markers":[]}\n'),
    ("mcpIndexMjs",     "mcp/rounds-sources/index.mjs",     "#!/usr/bin/env node\n// rounds-sources MCP (placeholder)\nprocess.stdin.resume();\n"),
]

DELIM = '###'

def read(rel, placeholder):
    p = BRAIN / rel
    if p.exists():
        return p.read_text(encoding="utf-8")
    return placeholder

def emit():
    lines = [
        "//",
        "//  BrainResources.swift",
        "//  rounds",
        "//",
        "//  GENERATED by tools/gen_brain_resources.py — do not edit by hand.",
        "//  Embeds the open-source Rounds \"brain\" (contract, prompts, sources MCP) so the",
        "//  app installs it into ~/Rounds for any user with no external files.",
        "//",
        "",
        "import Foundation",
        "",
        "nonisolated enum BrainResources {",
        '    static let brainVersion = "1.0.8"',
        "",
    ]
    for name, rel, placeholder in FILES:
        content = read(rel, placeholder)
        # Raw multiline string. Closing delimiter at column 0 so NO indentation is
        # stripped and the embedded content is preserved byte-for-byte.
        lines.append(f"    static let {name} = {DELIM}\"\"\"")
        lines.append(content.rstrip("\n"))
        lines.append(f"\"\"\"{DELIM}")
        lines.append("")
    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
    for name, rel, _ in FILES:
        p = BRAIN / rel
        print(f"  {name:16s} <- {rel}  {'OK' if p.exists() else 'PLACEHOLDER'}")

if __name__ == "__main__":
    emit()
